export const meals = [
  {
    id: "shawarma",
    name: "Kyckling Shawarma & Ris",
    description: "Innehåll: Kyckling shawarma, gurka, morot, ris.",
    price: 59.99,
    image: "https://i.ibb.co/gbj9crjb/IMAGE-2025-04-12-14-37-11.jpg",
    calories: 420,
    protein: 25,
  },
  {
    id: "spett",
    name: "Kyckling Spett & Ris",
    description: "Innehåll: Kyckling spett, gurka, morot, ris.",
    price: 59.99,
    image: "https://i.ibb.co/jPHLg8TR/IMAGE-2025-04-12-14-37-01.jpg",
    calories: 420,
    protein: 27,
  },
  {
    id: "lax",
    name: "Laxfile & Ris",
    description: "Innehåll: Lax, ris, grönsaker.",
    price: 69.99,
    image: "https://i.ibb.co/CpD0tsms/IMAGE-2025-04-19-22-36-26.jpg",
    calories: 475,
    protein: 36,
  },
  {
    id: "pasta",
    name: "Pasta Sallad",
    description: "Innehåll: Majs, Gurka, Kyckling & Curry, Feta ost",
    price: 69.99,
    image: "https://i.ibb.co/Cp5n3GNZ/IMAGE-2025-04-19-22-36-22.jpg",
    calories: 550,
    protein: 32,
  },
  {
    id: "cevapcici",
    name: "Cevapcici & Ris",
    description: "Innehåll: Cevapcici, gurka, morot, ris.",
    price: 59.99,
    image: "https://i.ibb.co/PZ2TrdBB/IMAGE-2025-04-12-14-37-06.jpg",
    calories: 380,
    protein: 16,
  },
  {
    id: "teriyaki",
    name: "Kyckling Teriyaki & Ris",
    description: "Innehåll: Kyckling teriyaki, ris, grönsaker.",
    price: 69.99,
    image: "https://i.ibb.co/GBR9NdL/IMAGE-2025-04-20-22-32-47.jpg",
    calories: 450,
    protein: 25,
  },
];
