CREATE TABLE "orders" (
	"id" integer PRIMARY KEY NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"address" text NOT NULL,
	"postal_code" varchar(20) NOT NULL,
	"city" varchar(100) NOT NULL,
	"comment" text,
	"door_code" varchar(20),
	"floor" varchar(10),
	"extra_comment" text,
	"delivery_date" date NOT NULL,
	"payment_method" varchar(50) NOT NULL,
	"swish_id" varchar(255),
	"swish_url" text,
	"qr_code_url" text,
	"payment_status" varchar(50),
	"total_price" numeric NOT NULL,
	"discount" numeric DEFAULT '0',
	"delivery_fee" numeric DEFAULT '0',
	"discount_applied" boolean DEFAULT false,
	"campaign_code" varchar(100),
	"terms_accepted" boolean NOT NULL,
	"created_at" timestamp DEFAULT now()
);
